apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service
spec:
  type: NodePort
  selector:
    app: flask-hello
  ports:
    - port: 80         # external port (what you use in browser)
      targetPort: 5000 # app's port inside container
      nodePort: 30080  # Kubernetes node port (custom, between 30000–32767)
